# Generated by Django 2.2.4 on 2019-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=10000)),
                ('representation', models.CharField(max_length=10000)),
                ('arguments', models.CharField(max_length=10000)),
                ('stacktrace', models.CharField(max_length=10000)),
                ('ts_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
